[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
libraries = ['src/PreimageKeyLib.sol:PreimageKeyLib:0x0000000000000000000000000000000000007331']
optimizer = true
optimizer_runs = 999999

# See more config options https://github.com/foundry-rs/foundry/tree/master/config